### ISSUE TITLE
Add shortname for flags

### ISSUE THREAD

**Issue by CodeFanaticX** [sawyersteven/ArgSharp#1]
I just discovered this great argument parser.
Could you please allow shortname for flags as well?

e.g. [FlagArgument(-i, --info, "description")]

**Comment by kestrel-x86** [comment]
I'll push an update soon that allows this. I didn't originally include it because I wanted to be able to be able to have just shortname, or just longname, or both and then I kind of forgot to get back to it.

I'll ping you here when I get everything testing properly and the new version is live on nuget.

**Comment by CodeFanaticX** [comment]
Thank you very much :) This is the best argument parser I've tested so far which include all my needs

**Comment by kestrel-x86** [comment]
https://www.nuget.org/packages/ArgSharp

All ready to go. I'm glad you enjoy using it.

@wv-lover
